spring.application.name=mahasiswa-api
spring.datasource.url=jdbc:postgresql://localhost:5432/db_mahasiswa
spring.datasource.username=postgres
spring.datasource.password=Wismar123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true